### ISSUE TITLE
User Edit Page field validation 

### ISSUE THREAD

**Issue by karthickrajak** [TheOpenCMS/TheOpenCMS#1]
Hi, 
    I've just created the account in theopencms.org (id7), I tried to change the login field with my email instead of id7. 
The update operation got succeed, ( Listed in users page after I re-logged in ). 
If I access the myprofile page, I m receiving 404 error, Here is the link for [My-profile](https://theopencms.org/users/karthickraja.bksystems@gmail.com/edit)

Apart from I found below points, But I don't have any idea either those were issues. 

- I updated the user details of user Kushal(id6). I don't think I am a master/super user.
- The password prompt on the my-profile page is just a input box, the text were visible

**Comment by the-teacher** [comment]
Hello @karthickrajak ! Thank you for your feedback!
I'll check it asap. 👍

**Comment by the-teacher** [comment]
@karthickrajak you found very interesting case. That is why it's so important to release early versions. Great job! Going to fix it soon. Thank you for your amazing report!

**Comment by the-teacher** [comment]
> I tried to change the login field with my email instead of id7
> If I access the myprofile page, I m receiving 404 error, Here is the link for My-profile

Done. Page is available by address `http://localhost:3000/users/karthickraja-bksystems-gmail-com`
Definitely Login has to work like a slug param and don't contain chars like `.` or `@`

**Comment by the-teacher** [comment]
> I updated the user details of user Kushal(id6). I don't think I am a master/super user.
@karthickrajak What have exactly you done? Why do you think you updated details of user with ID=6?

**Comment by the-teacher** [comment]
@karthickrajak password fields are already fixed. I reproduces the problem with user's permissions. Thanks!

**Comment by the-teacher** [comment]
@karthickrajak all issues were fixed. Thank you very much for your report and help! 👍

**Comment by karthickrajak** [comment]
Nice work @the-teacher.
Keep going.

**Comment by karthickrajak** [comment]
> @karthickrajak What have exactly you done? Why do you think you updated details of user with ID=6?

I tried to revoke my changes by tampering another user update request.
To generate a user update form, I accessed the another id page. 
By then I changed his about information(Added his first name and last name). 

Any how, Those request's were got denial response now.
